spring:
  profiles:
    active: local

logging:
  level:
    com.akretsev: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c:%L - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c:%L - %m%n"
  file:
    name: ./logs/dispatcher.log
  logback:
    rolling policy:
      max-file-size: 5MB

